### PR TITLE
Add Korean

### PR DESCRIPTION
**Pull request by VenusGirl**

### CODE REVIEW

**Review by VenusGirl — COMMENTED** [review]
Fix...

**Review by VenusGirl — COMMENTED** [review]
Add Korean

**Review by Timthreetwelve — APPROVED** [review]
Thank you!

**Comment by Timthreetwelve** [comment]
@VenusGirl, I appreciate your contribution of the new Korean translation. It always makes my day when I see the notifications from GitHub!

If you wouldn't mind, and have the time, would you please update the ko-KR file in [Get My IP](https://github.com/Timthreetwelve/GetMyIP)? I'm close to releasing an updated version and it would be great to have the translations up to date.

Thanks again,
Tim

**Comment by Timthreetwelve** [comment]
@VenusGirl, I'm finally getting close to releasing the next version of [My Scheduled Tasks](https://github.com/Timthreetwelve/MyScheduledTasks). I want to thank you again for adding the Korean language.

I copied 18 strings, mostly related to the newly added Export/Import of Settings, which had already been translated. Would you check `MsgText_ImportSettingsRestart`, I changed the application name and want to verify that the message is correct.

Also, would you translate the `MsgText_ErrorReadingSettings` string? It is the only string that is missing from the ko-KR file.

I hope this finds you well. Thanks again.

Tim

**Pull request merged**
